name: Build FAISS index from TXT

on:
  workflow_dispatch:
  push:
    paths:
      - "txts/**.txt"
      - "build_index.py"
      - ".github/workflows/build-index.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install faiss-cpu openai tqdm numpy

      - name: Build index
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python build_index.py

      - name: Commit index files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index/*
          git commit -m "Update FAISS index" || echo "No changes to commit"
          git push
